---
- name: Install EPEL Repo
  yum:
    name: epel-release
    state: present
- name: Install nginx
  yum:
    name: nginx
    state: present
- name: Nginx host config file
  template:
    src: assg1.conf.j2
    dest: /etc/nginx/conf.d/assg1.conf
- name: Nginx main config file 
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: start nginx
  service:
    name: nginx
    state: started

- name: Enable port 80 in firewall
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld