---
 - hosts: nginx_server
   become: yes
   gather_facts: no
  #  vars:
  #   - ansible_ssh_port : 2222
   roles:
    - server_hardening
    - nginx_server
    - nginx-hardening

 - hosts: app_server
   become: yes
   gather_facts: no
  #  vars:
  #   - ansible_ssh_port : 2222
   roles:
    - server_hardening
    - app_server
