---
 - hosts: nginx_server
   remote_user: amar
   become: yes
   tasks:
     - include_vars: var.yml
     - name: Install nginx
       yum:
         name: nginx
         state: present
     - name: Nginx host config file
       template:
         src: assg1.conf.j2
         dest: /etc/nginx/conf.d/assg1.conf
     - name: Nginx main config file 
       template:
         src: nginx.conf.j2
         dest: /etc/nginx/nginx.conf
     - name: start nginx
       service:
         name: nginx
         state: started

 - hosts: app_server
   remote_user: amar
   become: yes
   tasks:
     - include_vars: var.yml
     - name: Install required packages
       yum:
         name: ['python3', 'python3-setuptool', 'python-setuptools']
         state: present
     - name: Create user for app
       user:
         name: apprun
     - name: Copy app code
       copy:
         src: ../assg1
         dest: /opt/
         owner: apprun
         group: apprun
     - name: Install virtualenv via pip
       pip:
         name: virtualenv
         executable: pip3
     - name: Create virtualenv and install dependencies
       pip: 
         requirements: /opt/assg1/requirements.txt 
         virtualenv: /opt/venv 
         virtualenv_python: /bin/python3
         virtualenv_command: python3 -m virtualenv
     - name: Gunicorn Config file
       template:
         src: assg1-app.service.j2
         dest: /etc/systemd/system/assg1-app.service
     - name: start app
       service:
         name: assg1-app
         state: started
  
