---

##Install and configure auditd
- name: install auditd package 
  yum:
    name: audit
    state: present

- name: configure auditd 
  template:
    src: 'auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'

# Disable coredump via limits
- name: create additional limits config file 
  pam_limits:
    dest: '/etc/security/limits.d/10.hardcore.conf'
    domain: '*'
    limit_type: hard
    limit_item: core
    value: '0'

- name: set 10.hardcore.conf perms to 0400 and root ownership
  file:
    path: /etc/security/limits.d/10.hardcore.conf
    owner: 'root'
    group: 'root'
    mode: '0440'

# Configure login.defs
- name: Login.defs configuration
  template:
    src: 'login.defs.j2'
    dest: '/etc/login.defs'
    owner: 'root'
    group: 'root'
    mode: '0444'
 
#Securing shadow file and passwd file    
- name: change shadow ownership to root and mode to 0600 
  file:
    dest: '/etc/shadow'
    owner: 'root'
    group: 'root'
    mode: '0000'

- name: change passwd ownership to root and mode to 0644 
  file:
    dest: '/etc/passwd'
    owner: 'root'
    group: 'root'
    mode: '0644'

#Proc filesystem

- name: set option hidepid for proc filesystem
  mount:
    path: /proc
    src: proc
    fstype: proc
    opts: 'rw,nosuid,nodev,noexec,relatime,hidepid=2'
    state: present

- name: configure pam_pwquality via central system-auth config
  template:
    src: 'system-auth-ac.j2'
    dest: '/etc/pam.d/system-auth-ac'
    mode: '0640'
    owner: 'root'
    group: 'root'

- name: Upgrade Password Hashing Algorithm to SHA-512
  template:
    src: 'libuser.conf.j2'
    dest: '/etc/libuser.conf'
    mode: '0640'
    owner: 'root'
    group: 'root'

# sysctl configurations
- name: protect sysctl.conf
  file:
    path: '/etc/sysctl.conf'
    owner: 'root'
    group: 'root'
    mode: '0440'

- name: set Daemon umask 
  lineinfile:
        path: /etc/sysconfig/init
        line: 'umask 027'

- name: Change various sysctl-settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

#Yum   
- name: remove unused repositories
  file:
    name: '/etc/yum.repos.d/{{ item }}.repo'
    state: 'absent'
  with_items:
    - 'CentOS-Debuginfo'
    - 'CentOS-Media'
    - 'CentOS-Vault'

- name: get yum-repository-files
  shell: 'find /etc/yum.repos.d/ -type f -name *.repo'
  changed_when: False
  register: yum_repos

- name: activate gpg-check for config files
  replace:
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 1'
  with_flattened:
    - '/etc/yum.conf'
    - '{{ yum_repos.stdout_lines| default([]) }}'

- name: remove deprecated or insecure packages 
  yum:
    name: ['xinetd', 'inetd', 'ypserv', 'telnet-server', 'rsh-server', 'prelink']
    state: 'absent'

##SSH##

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: "^PermitRootLogin"
    state: present
  notify: restart sshd

- name: Adjust idle sessions timeout
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item.line }}{{ item.value }}"
    regexp: "^{{ item.line }}"
    state: present
  with_items:
    - { line: 'ClientAliveInterval ', value: '300' }
    - { line: 'ClientAliveCountMax ', value: '2' }
  notify: restart sshd

- name: Enable port 2222 in firewall
  firewalld:
    port: 2222/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: Change default SSH server port
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port 2222"
    regexp: "^Port"
    state: present
  notify: restart sshd


