---
- name: Install required packages
  yum:
    name: ['python3', 'python3-setuptools', 'python-setuptools']
    state: present
- name: Create user for app
  user:
    name: apprun
- name: Copy app code
  copy:
    src: assg1
    dest: /opt/
    owner: apprun
    group: apprun
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
- name: Create virtualenv and install dependencies
  pip: 
    requirements: /opt/assg1/requirements.txt 
    virtualenv: /opt/venv 
    virtualenv_python: /bin/python3
    virtualenv_command: python3 -m virtualenv
- name: Gunicorn Config file
  template:
    src: sliceit.service.j2
    dest: /etc/systemd/system/sliceit.service
  notify: start sliceit

- name: Enable port 8000 in firewall
  firewalld:
    port: 8000/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

